version: '3.4'

services:
    TS_mongo:
        image: mongo
        command:
            - mongod
#            - --replSet
#            - "rs0"
        expose:
            - ${MONGO_PORT}

    Users_redis:
        image: redis
        expose:
            - "6379"

    Users:
        image: nhex2/users
        depends_on:
            - TS_mongo
        expose:
            - "${TS_WS_PORT}"
            - "${TS_HTTP_PORT}"
        ports:
            - "8000:${TS_HTTP_PORT}" # this is just for initiating board on TS
        command:
            ["${TS_WS_PORT}", "${TS_HTTP_PORT}"]

    TSS:
        image: nhex2/tss
        depends_on:
            - TS
        expose:
            - "${TSS_WS_PORT}"
            - "${TSS_HTTP_CONTROL_PORT}"
        ports:
              - "${TSS_WS_PORT}:${TSS_WS_PORT}"
              - "${TSS_HTTP_CONTROL_PORT}:${TSS_HTTP_CONTROL_PORT}"
        command:
            ["${TSS_HTTP_CONTROL_PORT}", "${TSS_WS_PORT}", "TM", "Users"]

    Users_mongo:
        image: mongo
        command:
            - mongod
#            - --replSet
#            - "rs0"
        expose:
            - ${MONGO_PORT}

    Users_redis:
        image: redis
        expose:
            - "6379"

    Users:
        image: nhex2/users
        depends_on:
            - Users_mongo
            - Users_redis
        ports:
            - "8001:${USERS_PORT}" # this is just for testing
        expose:
            - "${USERS_PORT}"
#         ports:
#             - "${USERS_PORT}:${USERS_PORT}"
