version: '3.4'

services:
    TS_mongo:
        image: mongo
        command:
            - mongod
        expose:
            - ${MONGO_PORT}

    TS:
        image: nhex2/ts
        depends_on:
            - TS_mongo
        expose:
            - "${TS_WS_PORT}"
            - "${TS_HTTP_PORT}"
        environment:
            TS_WS_PORT: "${TS_WS_PORT}"
            TS_HTTP_PORT: "${TS_HTTP_PORT}"

    TSS1:
        image: nhex2/tss
        depends_on:
            TM:
                condition: service_started
        expose:
            - "${TSS1_EXTERNAL_CONTROL_ADDR}"
        environment:
            TSS_INTERNAL_CONTROL_PORT: ${TSS_INTERNAL_CONTROL_PORT}
            TSS_INTERNAL_CLIENTS_PORT: ${TSS_INTERNAL_CLIENTS_PORT}
            TSS_EXTERNAL_CONTROL_ADDR: ${TSS1_EXTERNAL_CONTROL_ADDR}
            TSS_EXTERNAL_CLIENTS_ADDR: ${TSS1_EXTERNAL_CLIENTS_ADDR}
            TM_TSS_PORT: ${TM_TSS_PORT}
            USERS_PORT: ${USERS_PORT}
        ports:
              - "${TSS_INTERNAL_CLIENTS_PORT}:${TSS_INTERNAL_CLIENTS_PORT}"

    TM_maria:
        image: mariadb
        expose:
            - "${MARIA_PORT}"
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
        healthcheck:
            test: [ "CMD", "/usr/bin/mysql", "--execute", "SHOW DATABASES;"]
            interval: 5s
            timeout: 1s
            retries: 5
        command:
            "--init-file /data/application/init.sql"
        volumes:
            - ./init.sql:/data/application/init.sql

    TM:
        image: nhex2/tm
        depends_on:
            TM_maria:
                condition: service_healthy
        expose:
            - "${TM_TSS_PORT}"
            - "${TM_APP_PORT}"
        environment:
            TS_HTTP_PORT: "${TS_HTTP_PORT}"
            TS_WS_PORT: "${TS_WS_PORT}"
            TM_TSS_PORT: "${TM_TSS_PORT}"
            TM_APP_PORT: "${TM_APP_PORT}"
        ports:
            - "6666:${TM_APP_PORT}"

    Users_mongo:
        image: mongo
        command:
            - mongod
        expose:
            - ${MONGO_PORT}

    Users_redis:
        image: redis
        expose:
            - "6379"

    Users:
        image: nhex2/users
        depends_on:
            - Users_mongo
            - Users_redis
        ports:
            - "8001:${USERS_PORT}" # this is just for testing
        expose:
            - "${USERS_PORT}"
#         ports:
#             - "${USERS_PORT}:${USERS_PORT}"
