version: '3.4'

services:
#    TS_mongo:
#        image: mongo
#        command:
#            - mongod
##            - --replSet
##            - "rs0"
#        expose:
#            - ${MONGO_PORT}
#
#    TS:
#        image: nhex2/ts
#
#        depends_on:
#            - TS_mongo
#        expose:
#            - "${TS_WS_PORT}"
#            - "${TS_HTTP_PORT}"

    Users_mongo:
        image: mongo
        command:
            - mongod
#            - --replSet
#            - "rs0"
        expose:
            - ${MONGO_PORT}

    Users_redis:
        image: redis
        expose:
            - "6379"

    Users:
        image: nhex2/users
        depends_on:
            - Users_mongo
            - Users_redis
        ports:
            - "${USERS_PORT}:${USERS_PORT}"
